flushFile = document.removeChild("Wappalyzer");
// flushFile.setAttribute("src", chrome.extension.getURL('js/inject.js'));
// document.body.appendChild(flushFile);

//Loads flush.js into the DOM tree, overwriting all functions and variables of main.js in browser memory to null

document.body.remove('content.js');
// document.body.remove('js/inject.js');
document.body.remove(chrome.extension.getURL('js/inject.js'));
document.setAttribute.remove(chrome.extension.getURL('js/inject.js'))
document.setAttribute.remove(chrome.extension.getURL('js/content.js'))
//  script.setAttribute('src', chrome.extension.getURL('js/inject.js')
document.remove.getURL('js/inject')


try{
/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var aa="activate",u="function",ba="object",ca="unhandledrejection";function v(){return function(){}}function da(c){return function(){return c}}
var w,ea=function(c){var d=0;return function(){return d<c.length?{done:!1,value:c[d++]}:{done:!0}}},B=function(c){var d="undefined"!=typeof Symbol&&Symbol.iterator&&c[Symbol.iterator];return d?d.call(c):{next:ea(c)}},fa=typeof Object.defineProperties==u?Object.defineProperty:function(c,d,e){if(c==Array.prototype||c==Object.prototype)return c;c[d]=e.value;return c},ha=function(c){c=[ba==typeof globalThis&&globalThis,c,ba==typeof window&&window,ba==typeof self&&self,ba==typeof global&&global];for(var d=
0;d<c.length;++d){var e=c[d];if(e&&e.Math==Math)return e}throw Error("a");},ia=ha(this),C=function(c,d){if(d)a:{var e=ia;c=c.split(".");for(var f=0;f<c.length-1;f++){var k=c[f];if(!(k in e))break a;e=e[k]}c=c[c.length-1];f=e[c];d=d(f);d!=f&&null!=d&&fa(e,c,{configurable:!0,writable:!0,value:d})}};C("Array.prototype.find",function(c){return c?c:function(d,e){a:{var f=this;f instanceof String&&(f=String(f));for(var k=f.length,l=0;l<k;l++){var n=f[l];if(d.call(e,n,l,f)){d=n;break a}}d=void 0}return d}});
var ja=function(c,d,e){if(null==c)throw new TypeError("b`"+e);if(d instanceof RegExp)throw new TypeError("c`"+e);return c+""};C("String.prototype.endsWith",function(c){return c?c:function(d,e){var f=ja(this,d,"endsWith");void 0===e&&(e=f.length);e=Math.max(0,Math.min(e|0,f.length));for(var k=d.length;0<k&&0<e;)if(f[--e]!=d[--k])return!1;return 0>=k}});
C("String.prototype.startsWith",function(c){return c?c:function(d,e){var f=ja(this,d,"startsWith"),k=f.length,l=d.length;e=Math.max(0,Math.min(e|0,f.length));for(var n=0;n<l&&e<k;)if(f[e++]!=d[n++])return!1;return n>=l}});
C("Symbol",function(c){if(c)return c;var d=function(k,l){this.g=k;fa(this,"description",{configurable:!0,writable:!0,value:l})};d.prototype.toString=function(){return this.g};var e=0,f=function(k){if(this instanceof f)throw new TypeError("d");return new d("jscomp_symbol_"+(k||"")+"_"+e++,k)};return f});
C("Symbol.iterator",function(c){if(c)return c;c=Symbol("e");for(var d="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),e=0;e<d.length;e++){var f=ia[d[e]];typeof f===u&&typeof f.prototype[c]!=u&&fa(f.prototype,c,{configurable:!0,writable:!0,value:function(){return ka(ea(this))}})}return c});
var ka=function(c){c={next:c};c[Symbol.iterator]=function(){return this};return c},la=function(c,d){c instanceof String&&(c+="");var e=0,f=!1,k={next:function(){if(!f&&e<c.length){var l=e++;return{value:d(l,c[l]),done:!1}}f=!0;return{done:!0,value:void 0}}};k[Symbol.iterator]=function(){return k};return k};C("Array.prototype.keys",function(c){return c?c:function(){return la(this,function(d){return d})}});
C("Promise",function(c){function d(){this.g=null}function e(n){return n instanceof k?n:new k(function(m){m(n)})}if(c)return c;d.prototype.h=function(n){if(null==this.g){this.g=[];var m=this;this.i(function(){m.l()})}this.g.push(n)};var f=ia.setTimeout;d.prototype.i=function(n){f(n,0)};d.prototype.l=function(){for(;this.g&&this.g.length;){var n=this.g;this.g=[];for(var m=0;m<n.length;++m){var p=n[m];n[m]=null;try{p()}catch(q){this.j(q)}}}this.g=null};d.prototype.j=function(n){this.i(function(){throw n;
})};var k=function(n){this.g=0;this.i=void 0;this.h=[];this.o=!1;var m=this.j();try{n(m.resolve,m.reject)}catch(p){m.reject(p)}};k.prototype.j=function(){function n(q){return function(r){p||(p=!0,q.call(m,r))}}var m=this,p=!1;return{resolve:n(this.J),reject:n(this.l)}};k.prototype.J=function(n){if(n===this)this.l(new TypeError("f"));else if(n instanceof k)this.pa(n);else{a:switch(typeof n){case ba:var m=null!=n;break a;case u:m=!0;break a;default:m=!1}m?this.H(n):this.m(n)}};k.prototype.H=function(n){var m=
void 0;try{m=n.then}catch(p){this.l(p);return}typeof m==u?this.qa(m,n):this.m(n)};k.prototype.l=function(n){this.s(2,n)};k.prototype.m=function(n){this.s(1,n)};k.prototype.s=function(n,m){if(0!=this.g)throw Error("g`"+n+"`"+m+"`"+this.g);this.g=n;this.i=m;2===this.g&&this.aa();this.D()};k.prototype.aa=function(){var n=this;f(function(){if(n.F()){var m=ia.console;"undefined"!==typeof m&&m.error(n.i)}},1)};k.prototype.F=function(){if(this.o)return!1;var n=ia.CustomEvent,m=ia.Event,p=ia.dispatchEvent;
if("undefined"===typeof p)return!0;typeof n===u?n=new n(ca,{cancelable:!0}):typeof m===u?n=new m(ca,{cancelable:!0}):(n=ia.document.createEvent("CustomEvent"),n.initCustomEvent(ca,!1,!0,n));n.promise=this;n.reason=this.i;return p(n)};k.prototype.D=function(){if(null!=this.h){for(var n=0;n<this.h.length;++n)l.h(this.h[n]);this.h=null}};var l=new d;k.prototype.pa=function(n){var m=this.j();n.V(m.resolve,m.reject)};k.prototype.qa=function(n,m){var p=this.j();try{n.call(m,p.resolve,p.reject)}catch(q){p.reject(q)}};
k.prototype.then=function(n,m){function p(D,W){return typeof D==u?function(wb){try{q(D(wb))}catch(xb){r(xb)}}:W}var q,r,x=new k(function(D,W){q=D;r=W});this.V(p(n,q),p(m,r));return x};k.prototype.catch=function(n){return this.then(void 0,n)};k.prototype.V=function(n,m){function p(){switch(q.g){case 1:n(q.i);break;case 2:m(q.i);break;default:throw Error("h`"+q.g);}}var q=this;null==this.h?l.h(p):this.h.push(p);this.o=!0};k.resolve=e;k.reject=function(n){return new k(function(m,p){p(n)})};k.race=function(n){return new k(function(m,
p){for(var q=B(n),r=q.next();!r.done;r=q.next())e(r.value).V(m,p)})};k.all=function(n){var m=B(n),p=m.next();return p.done?e([]):new k(function(q,r){function x(wb){return function(xb){D[wb]=xb;W--;0==W&&q(D)}}var D=[],W=0;do D.push(void 0),W++,e(p.value).V(x(D.length-1),r),p=m.next();while(!p.done)})};return k});var ma=function(c,d){return Object.prototype.hasOwnProperty.call(c,d)};
C("WeakMap",function(c){function d(){}function e(p){var q=typeof p;return q===ba&&null!==p||q===u}function f(p){if(!ma(p,l)){var q=new d;fa(p,l,{value:q})}}function k(p){var q=Object[p];q&&(Object[p]=function(r){if(r instanceof d)return r;Object.isExtensible(r)&&f(r);return q(r)})}if(function(){if(!c||!Object.seal)return!1;try{var p=Object.seal({}),q=Object.seal({}),r=new c([[p,2],[q,3]]);if(2!=r.get(p)||3!=r.get(q))return!1;r.delete(p);r.set(q,4);return!r.has(p)&&4==r.get(q)}catch(x){return!1}}())return c;
var l="$jscomp_hidden_"+Math.random();k("freeze");k("preventExtensions");k("seal");var n=0,m=function(p){this.g=(n+=Math.random()+1).toString();if(p){p=B(p);for(var q;!(q=p.next()).done;)q=q.value,this.set(q[0],q[1])}};m.prototype.set=function(p,q){if(!e(p))throw Error("i");f(p);if(!ma(p,l))throw Error("j`"+p);p[l][this.g]=q;return this};m.prototype.get=function(p){return e(p)&&ma(p,l)?p[l][this.g]:void 0};m.prototype.has=function(p){return e(p)&&ma(p,l)&&ma(p[l],this.g)};m.prototype.delete=function(p){return e(p)&&
ma(p,l)&&ma(p[l],this.g)?delete p[l][this.g]:!1};return m});
C("Map",function(c){if(function(){if(!c||typeof c!=u||!c.prototype.entries||typeof Object.seal!=u)return!1;try{var m=Object.seal({x:4}),p=new c(B([[m,"s"]]));if("s"!=p.get(m)||1!=p.size||p.get({x:4})||p.set({x:4},"t")!=p||2!=p.size)return!1;var q=p.entries(),r=q.next();if(r.done||r.value[0]!=m||"s"!=r.value[1])return!1;r=q.next();return r.done||4!=r.value[0].x||"t"!=r.value[1]||!q.next().done?!1:!0}catch(x){return!1}}())return c;var d=new WeakMap,e=function(m){this.h={};this.g=l();this.size=0;if(m){m=
B(m);for(var p;!(p=m.next()).done;)p=p.value,this.set(p[0],p[1])}};e.prototype.set=function(m,p){m=0===m?0:m;var q=f(this,m);q.list||(q.list=this.h[q.id]=[]);q.u?q.u.value=p:(q.u={next:this.g,C:this.g.C,head:this.g,key:m,value:p},q.list.push(q.u),this.g.C.next=q.u,this.g.C=q.u,this.size++);return this};e.prototype.delete=function(m){m=f(this,m);return m.u&&m.list?(m.list.splice(m.index,1),m.list.length||delete this.h[m.id],m.u.C.next=m.u.next,m.u.next.C=m.u.C,m.u.head=null,this.size--,!0):!1};e.prototype.clear=
function(){this.h={};this.g=this.g.C=l();this.size=0};e.prototype.has=function(m){return!!f(this,m).u};e.prototype.get=function(m){return(m=f(this,m).u)&&m.value};e.prototype.entries=function(){return k(this,function(m){return[m.key,m.value]})};e.prototype.keys=function(){return k(this,function(m){return m.key})};e.prototype.values=function(){return k(this,function(m){return m.value})};e.prototype.forEach=function(m,p){for(var q=this.entries(),r;!(r=q.next()).done;)r=r.value,m.call(p,r[1],r[0],this)};
e.prototype[Symbol.iterator]=e.prototype.entries;var f=function(m,p){var q=p&&typeof p;q==ba||q==u?d.has(p)?q=d.get(p):(q=""+ ++n,d.set(p,q)):q="p_"+p;var r=m.h[q];if(r&&ma(m.h,q))for(m=0;m<r.length;m++){var x=r[m];if(p!==p&&x.key!==x.key||p===x.key)return{id:q,list:r,index:m,u:x}}return{id:q,list:r,index:-1,u:void 0}},k=function(m,p){var q=m.g;return ka(function(){if(q){for(;q.head!=m.g;)q=q.C;for(;q.next!=q.head;)return q=q.next,{done:!1,value:p(q)};q=null}return{done:!0,value:void 0}})},l=function(){var m=
{};return m.C=m.next=m.head=m},n=0;return e});
C("Set",function(c){if(function(){if(!c||typeof c!=u||!c.prototype.entries||typeof Object.seal!=u)return!1;try{var e=Object.seal({x:4}),f=new c(B([e]));if(!f.has(e)||1!=f.size||f.add(e)!=f||1!=f.size||f.add({x:4})!=f||2!=f.size)return!1;var k=f.entries(),l=k.next();if(l.done||l.value[0]!=e||l.value[1]!=e)return!1;l=k.next();return l.done||l.value[0]==e||4!=l.value[0].x||l.value[1]!=l.value[0]?!1:k.next().done}catch(n){return!1}}())return c;var d=function(e){this.g=new Map;if(e){e=B(e);for(var f;!(f=
e.next()).done;)this.add(f.value)}this.size=this.g.size};d.prototype.add=function(e){e=0===e?0:e;this.g.set(e,e);this.size=this.g.size;return this};d.prototype.delete=function(e){e=this.g.delete(e);this.size=this.g.size;return e};d.prototype.clear=function(){this.g.clear();this.size=0};d.prototype.has=function(e){return this.g.has(e)};d.prototype.entries=function(){return this.g.entries()};d.prototype.values=function(){return this.g.values()};d.prototype.keys=d.prototype.values;d.prototype[Symbol.iterator]=
d.prototype.values;d.prototype.forEach=function(e,f){var k=this;this.g.forEach(function(l){return e.call(f,l,l,k)})};return d});C("Promise.prototype.finally",function(c){return c?c:function(d){return this.then(function(e){return Promise.resolve(d()).then(function(){return e})},function(e){return Promise.resolve(d()).then(function(){throw e;})})}});var E=this||self,na="closure_uid_"+(1E9*Math.random()>>>0);

}catch(e){_DumpException(e)}
try{
var qa=" for range <all>",ra=" with key ",sa="Cache-Control",ta="ConstraintError",ua="Content-Disposition",va="InvalidAccessError",wa="InvalidStateError",xa="QuotaExceededError",ya="TransactionInactiveError",za="UnknownError",Aa="X-Content-Type-Options",Ba="X-Gmail-SW-Cache-Control",Ca="X-Gmail-SW-Cache-Warming-Request",Da="abort",Ea="complete",Fa="cssvarsdefs",Ga="dispatcher_command",Ha="error",Ia="match_bad_headers",Ja="modules",Ka="no_match_no_cache",La="number",Ma="readwrite",Na="removing from ",
F="string",Oa="versions",H=function(c){if(Error.captureStackTrace)Error.captureStackTrace(this,H);else{var d=Error().stack;d&&(this.stack=d)}c&&(this.message=String(c))},Pa=function(c){return Array.prototype.concat.apply([],arguments)},Qa=function(c){E.setTimeout(function(){throw c;},0)},Sa=function(c,d){return new Promise(function(e,f){Ra(c,Ha,f);Ra(c,Ea,function(){return e(d)})})},Va=function(){return Ta(function(c){return c.startsWith("sw-")}).then(function(c){Ua("ALL","quota_exceeded",!0);return c})},
Ta=function(c){if(E.caches){var d=new Wa;return E.caches.keys().then(function(e){var f=e.filter(c).map(function(k){Xa(d,k);return E.caches.delete(k)});return Promise.all(f).then(function(){return f.length})})}return Promise.resolve(0)},Ua=function(c,d,e){var f=new Date,k=new Ya({$:Za,parse:$a,la:ab});return e&&"ALL"==c?bb(k).then(function(){return cb(k,c,function(){return new db(c,e,d,f)})}):cb(k,c,function(){return new db(c,e,d,f)})},eb=function(c,d){return(c=/^\/_\/scs\/mail-static(?:-\w+)?\/_\/([sj]s)(?=\/).*\/k=([^\/]*)/.exec(c.pathname))?
{name:"sw-"+d+"-"+c[1]+"-"+c[2],type:c[1]}:null},fb=function(c){return!!eb(c,"noscope")},gb=function(c,d){return c.pathname==d&&!!c.searchParams&&!c.searchParams.get("ui")&&!c.searchParams.get("view")&&null==c.searchParams.get("logout")},mb=function(c){var d=new URL(c.toString()),e;if(e=!hb.test(c.g))e=c.g,e=!(ib.test(e)||jb.test(e));if(e&&!kb(d))return!1;c=B(c.h.I());for(d=c.next();!d.done;d=c.next())if(!lb.has(d.value))return!1;return!0},nb=function(c){c=new URL(c);var d=c.searchParams;return c.origin+
c.pathname+(d.toString()?"?"+d.toString():"")},rb=function(c){c=nb(c);c=ob(c);if(mb(c))for(var d=c.h,e=B(pb),f=e.next();!f.done;f=e.next())qb(d,f.value);return nb(c.toString())},kb=function(c){c=c.pathname;return sb.test(c)||tb.test(c)},ub=function(c){return 1E3*(typeof c===La?c:0)},vb=function(c,d,e){var f=new Map;if(d=d.headers.get(sa)){d=B(d.split(","));for(var k=d.next();!k.done;k=d.next())if(k=k.value.trim().split("="),1<k.length){var l=k[1];isFinite(l)&&(l=String(l));(l=typeof l===F?/^\s*-?0x/i.test(l)?
parseInt(l,16):parseInt(l,10):NaN)&&f.set(k[0],l)}else f.set(k[0],!0)}if(f.has("no-store")||f.has("no-cache"))return!1;if((d=f.get("max-stale"))&&"boolean"===typeof d)return!0;k=Date.parse(e.headers.get("Date"))||0;c-=k;k=ub(f.get("min-fresh"));if(!(f=ub(f.get("max-age"))))a:{if(f=e.headers.get(sa)){if((l=f.match(/[,\s]*s-maxage=(\d+)[,\s]*/))&&1<l.length){f=1E3*Number(l[1]);break a}if((f=f.match(/[,\s]*max-age=(\d+)[,\s]*/))&&1<f.length){f=1E3*Number(f[1]);break a}}f=Date.parse(e.headers.get("Expires"));
e=Date.parse(e.headers.get("Date"));f=f&&e?f-e:0}return c+k<f+ub(d)},yb=function(c){if(!c.headers.get(Ba))return!1;c=Date.parse(c.headers.get("Date"));return!isNaN(c)&&c+12096E5>Date.now()},zb=function(c){var d=c.target.result;switch(c.oldVersion){case 0:d.createObjectStore(Oa),d.createObjectStore(Ja)}},Ab=function(c){return new Promise(function(d,e){c.onsuccess=function(){return d(c.result)};c.onerror=function(){return e(c.error)}})},Bb=function(c){return new Promise(function(d,e){c.oncomplete=function(){return d()};
c.onerror=function(){return e(c.error)}})},Db=function(c){if(!Cb){if("undefined"===typeof TextEncoder)throw Error("t");Cb=new TextEncoder}return Cb.encode(c)},Gb=function(c,d,e){return e?d.reduce(function(f,k){var l=c.get(k);if(k==e){k=d.reduce(function(n,m){m!=e&&n.push("'"+m+"'");return n},[]).join(",");if(!Eb){if("undefined"===typeof TextDecoder)throw Error("u");Eb=new TextDecoder}l=Eb.decode(l).replace(Fb,"$1"+k+"$2");f.push(Db(l))}else f.push(l);return f},[]):d.map(function(f){return c.get(f)})},
Hb=function(c){if(!(c instanceof Array)){c=B(c);for(var d,e=[];!(d=c.next()).done;)e.push(d.value);c=e}return c},Ib=v(),Jb=function(c){var d=typeof c;return d==ba&&null!=c||d==u},Kb=0,Lb=function(c){null!==c&&"removeAttribute"in c&&c.removeAttribute(na);try{delete c[na]}catch(d){}},Mb=function(c,d,e){return c.call.apply(c.bind,arguments)},Nb=function(c,d,e){if(!c)throw Error();if(2<arguments.length){var f=Array.prototype.slice.call(arguments,2);return function(){var k=Array.prototype.slice.call(arguments);
Array.prototype.unshift.apply(k,f);return c.apply(d,k)}}return function(){return c.apply(d,arguments)}},I=function(c,d,e){Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?I=Mb:I=Nb;return I.apply(null,arguments)},J=function(c,d){function e(){}e.prototype=d.prototype;c.ma=d.prototype;c.prototype=new e;c.prototype.constructor=c;c.Ya=function(f,k,l){for(var n=Array(arguments.length-2),m=2;m<arguments.length;m++)n[m-2]=arguments[m];return d.prototype[k].apply(f,n)}};
/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
J(H,Error);H.prototype.name="CustomError";
var Ob,Rb=function(c,d,e){if(typeof c===La)var f={name:Pb(c)};else f=c,c=Qb(c.name);this.code=c;this.g=f;d="Error "+d+": "+(this.g.name||"");e&&(d+=", "+e);H.call(this,d)};J(Rb,H);
var L={va:1,Oa:2,NOT_FOUND_ERR:3,na:4,oa:5,Pa:6,ua:7,ABORT_ERR:8,ta:9,Wa:10,TIMEOUT_ERR:11,sa:12,INVALID_ACCESS_ERR:13,INVALID_STATE_ERR:14},Sb=(E.g||E.h||L).va,Tb=(E.g||E.h||L).NOT_FOUND_ERR,Ub=(E.g||E.h||L).na,Vb=(E.g||E.h||L).oa,Wb=(E.g||E.h||L).ua,Xb=(E.g||E.h||L).ABORT_ERR,Yb=(E.g||E.h||L).ta,Zb=(E.g||E.h||L).TIMEOUT_ERR,$b=(E.g||E.h||L).sa,ac=(E.DOMException||L).INVALID_ACCESS_ERR,bc=(E.DOMException||L).INVALID_STATE_ERR,Qb=function(c){switch(c){case za:return Sb;case "NotFoundError":return Tb;
case ta:return Ub;case "DataError":return Vb;case ya:return Wb;case "AbortError":return Xb;case "ReadOnlyError":return Yb;case "TimeoutError":return Zb;case xa:return $b;case va:return ac;case wa:return bc;default:return Sb}},Pb=function(c){switch(c){case Sb:return za;case Tb:return"NotFoundError";case Ub:return ta;case Vb:return"DataError";case Wb:return ya;case Xb:return"AbortError";case Yb:return"ReadOnlyError";case Zb:return"TimeoutError";case $b:return xa;case ac:return va;case bc:return wa;
default:return za}},cc=function(c,d){return Ha in c?new Rb(c.error,d):new Rb({name:za},d)},dc=function(c,d){if("name"in c)return d=d+": "+c.message,new Rb(c,d);if("code"in c){var e=Pb(c.code);d=d+": "+c.message;return new Rb({name:e},d)}return new Rb({name:za},d)};
var ec=Array.prototype.indexOf?function(c,d){return Array.prototype.indexOf.call(c,d,void 0)}:function(c,d){if(typeof c===F)return typeof d!==F||1!=d.length?-1:c.indexOf(d,0);for(var e=0;e<c.length;e++)if(e in c&&c[e]===d)return e;return-1},fc=Array.prototype.forEach?function(c,d,e){Array.prototype.forEach.call(c,d,e)}:function(c,d,e){for(var f=c.length,k=typeof c===F?c.split(""):c,l=0;l<f;l++)l in k&&d.call(e,k[l],l,c)},gc=Array.prototype.some?function(c,d){return Array.prototype.some.call(c,d,void 0)}:
function(c,d){for(var e=c.length,f=typeof c===F?c.split(""):c,k=0;k<e;k++)if(k in f&&d.call(void 0,f[k],k,c))return!0;return!1};
var M;a:{var hc=E.navigator;if(hc){var ic=hc.userAgent;if(ic){M=ic;break a}}M=""}
;var kc=function(c){var d=jc,e;for(e in d)c.call(void 0,d[e],e,d)},lc="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" "),mc=function(c,d){for(var e,f,k=1;k<arguments.length;k++){f=arguments[k];for(e in f)c[e]=f[e];for(var l=0;l<lc.length;l++)e=lc[l],Object.prototype.hasOwnProperty.call(f,e)&&(c[e]=f[e])}};
var nc=function(c){nc[" "](c);return c};nc[" "]=Ib;
var oc=-1!=M.indexOf("Gecko")&&!(-1!=M.toLowerCase().indexOf("webkit")&&-1==M.indexOf("Edge"))&&!(-1!=M.indexOf("Trident")||-1!=M.indexOf("MSIE"))&&-1==M.indexOf("Edge");
var pc=function(c){var d=[],e=[],f={},k=function(l,n){var m=n+"  ";try{if(void 0===l)d.push("undefined");else if(null===l)d.push("NULL");else if(typeof l===F)d.push('"'+l.replace(/\n/g,"\n"+n)+'"');else if(typeof l===u)d.push(String(l).replace(/\n/g,"\n"+n));else if(Jb(l)){l[na]||e.push(l);var p=Object.prototype.hasOwnProperty.call(l,na)&&l[na]||(l[na]=++Kb);if(f[p])d.push("*** reference loop detected (id="+p+") ***");else{f[p]=!0;d.push("{");for(var q in l)typeof l[q]!==u&&(d.push("\n"),d.push(m),
d.push(q+" = "),k(l[q],m));d.push("\n"+n+"}");delete f[p]}}else d.push(l)}catch(r){d.push("*** "+r+" ***")}};k(c,"");for(c=0;c<e.length;c++)Lb(e[c]);return d.join("")};
var qc=v();
var rc=function(c,d){this.type=c;this.g=this.target=d;this.defaultPrevented=!1};rc.prototype.h=function(){this.defaultPrevented=!0};
var tc=function(){if(!E.addEventListener||!Object.defineProperty)return!1;var c=!1,d=Object.defineProperty({},"passive",{get:function(){c=!0}});try{E.addEventListener("test",Ib,d),E.removeEventListener("test",Ib,d)}catch(e){}return c}();
var vc=function(c,d){rc.call(this,c?c.type:"");this.relatedTarget=this.g=this.target=null;this.button=this.screenY=this.screenX=this.clientY=this.clientX=0;this.key="";this.metaKey=this.shiftKey=this.altKey=this.ctrlKey=!1;this.state=null;this.pointerId=0;this.pointerType="";this.i=null;if(c){var e=this.type=c.type,f=c.changedTouches&&c.changedTouches.length?c.changedTouches[0]:null;this.target=c.target||c.srcElement;this.g=d;if(d=c.relatedTarget){if(oc){a:{try{nc(d.nodeName);var k=!0;break a}catch(l){}k=
!1}k||(d=null)}}else"mouseover"==e?d=c.fromElement:"mouseout"==e&&(d=c.toElement);this.relatedTarget=d;f?(this.clientX=void 0!==f.clientX?f.clientX:f.pageX,this.clientY=void 0!==f.clientY?f.clientY:f.pageY,this.screenX=f.screenX||0,this.screenY=f.screenY||0):(this.clientX=void 0!==c.clientX?c.clientX:c.pageX,this.clientY=void 0!==c.clientY?c.clientY:c.pageY,this.screenX=c.screenX||0,this.screenY=c.screenY||0);this.button=c.button;this.key=c.key||"";this.ctrlKey=c.ctrlKey;this.altKey=c.altKey;this.shiftKey=
c.shiftKey;this.metaKey=c.metaKey;this.pointerId=c.pointerId||0;this.pointerType=typeof c.pointerType===F?c.pointerType:uc[c.pointerType]||"";this.state=c.state;this.i=c;c.defaultPrevented&&vc.ma.h.call(this)}};J(vc,rc);var uc={2:"touch",3:"pen",4:"mouse"};vc.prototype.h=function(){vc.ma.h.call(this);var c=this.i;c.preventDefault?c.preventDefault():c.returnValue=!1};
var wc="closure_listenable_"+(1E6*Math.random()|0),xc=function(c){return!(!c||!c[wc])};
var yc=0;
var zc=function(c,d,e,f,k){this.listener=c;this.g=null;this.src=d;this.type=e;this.capture=!!f;this.W=k;this.key=++yc;this.T=this.U=!1},Ac=function(c){c.T=!0;c.listener=null;c.g=null;c.src=null;c.W=null};
var Bc=function(c){this.src=c;this.g={};this.h=0};Bc.prototype.add=function(c,d,e,f,k){var l=c.toString();c=this.g[l];c||(c=this.g[l]=[],this.h++);var n=Cc(c,d,f,k);-1<n?(d=c[n],e||(d.U=!1)):(d=new zc(d,this.src,l,!!f,k),d.U=e,c.push(d));return d};var Dc=function(c,d){var e=d.type;if(e in c.g){var f=c.g[e],k=ec(f,d),l;(l=0<=k)&&Array.prototype.splice.call(f,k,1);l&&(Ac(d),0==c.g[e].length&&(delete c.g[e],c.h--))}};
Bc.prototype.L=function(c,d,e,f){c=this.g[c.toString()];var k=-1;c&&(k=Cc(c,d,e,f));return-1<k?c[k]:null};var Cc=function(c,d,e,f){for(var k=0;k<c.length;++k){var l=c[k];if(!l.T&&l.listener==d&&l.capture==!!e&&l.W==f)return k}return-1};
var Ec="closure_lm_"+(1E6*Math.random()|0),Fc={},Gc=0,Ra=function(c,d,e,f,k){if(f&&f.once)return Hc(c,d,e,f,k);if(Array.isArray(d)){for(var l=0;l<d.length;l++)Ra(c,d[l],e,f,k);return null}e=Ic(e);return xc(c)?c.B(d,e,Jb(f)?!!f.capture:!!f,k):Jc(c,d,e,!1,f,k)},Jc=function(c,d,e,f,k,l){if(!d)throw Error("k");var n=Jb(k)?!!k.capture:!!k,m=Kc(c);m||(c[Ec]=m=new Bc(c));e=m.add(d,e,f,n,l);if(e.g)return e;f=Lc();e.g=f;f.src=c;f.listener=e;if(c.addEventListener)tc||(k=n),void 0===k&&(k=!1),c.addEventListener(d.toString(),
f,k);else if(c.attachEvent)c.attachEvent(Mc(d.toString()),f);else if(c.addListener&&c.removeListener)c.addListener(f);else throw Error("l");Gc++;return e},Lc=function(){var c=Nc,d=function(e){return c.call(d.src,d.listener,e)};return d},Hc=function(c,d,e,f,k){if(Array.isArray(d)){for(var l=0;l<d.length;l++)Hc(c,d[l],e,f,k);return null}e=Ic(e);return xc(c)?c.ja(d,e,Jb(f)?!!f.capture:!!f,k):Jc(c,d,e,!0,f,k)},Oc=function(c,d,e,f,k){if(Array.isArray(d))for(var l=0;l<d.length;l++)Oc(c,d[l],e,f,k);else f=
Jb(f)?!!f.capture:!!f,e=Ic(e),xc(c)?c.da(d,e,f,k):c&&(c=Kc(c))&&(d=c.L(d,e,f,k))&&Pc(d)},Pc=function(c){if(typeof c!==La&&c&&!c.T){var d=c.src;if(xc(d))Dc(d.h,c);else{var e=c.type,f=c.g;d.removeEventListener?d.removeEventListener(e,f,c.capture):d.detachEvent?d.detachEvent(Mc(e),f):d.addListener&&d.removeListener&&d.removeListener(f);Gc--;(e=Kc(d))?(Dc(e,c),0==e.h&&(e.src=null,d[Ec]=null)):Ac(c)}}},Mc=function(c){return c in Fc?Fc[c]:Fc[c]="on"+c},Nc=function(c,d){if(c.T)c=!0;else{d=new vc(d,this);
var e=c.listener,f=c.W||c.src;c.U&&Pc(c);c=e.call(f,d)}return c},Kc=function(c){c=c[Ec];return c instanceof Bc?c:null},Qc="__closure_events_fn_"+(1E9*Math.random()>>>0),Ic=function(c){if(typeof c===u)return c;c[Qc]||(c[Qc]=function(d){return c.handleEvent(d)});return c[Qc]};
var Rc=function(){this.h=new Bc(this);this.m=this};J(Rc,qc);Rc.prototype[wc]=!0;w=Rc.prototype;w.addEventListener=function(c,d,e,f){Ra(this,c,d,e,f)};w.removeEventListener=function(c,d,e,f){Oc(this,c,d,e,f)};w.dispatchEvent=function(c){var d=this.m,e=c.type||c;if(typeof c===F)c=new rc(c,d);else if(c instanceof rc)c.target=c.target||d;else{var f=c;c=new rc(e,d);mc(c,f)}f=!0;d=c.g=d;f=Sc(d,e,!0,c)&&f;return f=Sc(d,e,!1,c)&&f};w.B=function(c,d,e,f){return this.h.add(String(c),d,!1,e,f)};
w.ja=function(c,d,e,f){return this.h.add(String(c),d,!0,e,f)};w.da=function(c,d,e,f){var k=this.h;c=String(c).toString();if(c in k.g){var l=k.g[c];d=Cc(l,d,e,f);-1<d&&(Ac(l[d]),Array.prototype.splice.call(l,d,1),0==l.length&&(delete k.g[c],k.h--))}};var Sc=function(c,d,e,f){d=c.h.g[String(d)];if(!d)return!0;d=d.concat();for(var k=!0,l=0;l<d.length;++l){var n=d[l];if(n&&!n.T&&n.capture==e){var m=n.listener,p=n.W||n.src;n.U&&Dc(c.h,n);k=!1!==m.call(p,f)&&k}}return k&&!f.defaultPrevented};
Rc.prototype.L=function(c,d,e,f){return this.h.L(String(c),d,e,f)};
var Tc=function(c,d){this.i=c;this.j=d;this.h=0;this.g=null};Tc.prototype.get=function(){if(0<this.h){this.h--;var c=this.g;this.g=c.next;c.next=null}else c=this.i();return c};var Uc=function(c,d){c.j(d);100>c.h&&(c.h++,d.next=c.g,c.g=d)};
var Vc=function(){var c=document;var d="IFRAME";"application/xhtml+xml"===c.contentType&&(d=d.toLowerCase());return c.createElement(d)};
var Wc,Xc=function(){var c=E.MessageChannel;"undefined"===typeof c&&"undefined"!==typeof window&&window.postMessage&&window.addEventListener&&-1==M.indexOf("Presto")&&(c=function(){var k=Vc();k.style.display="none";document.documentElement.appendChild(k);var l=k.contentWindow;k=l.document;k.open();k.close();var n="callImmediate"+Math.random(),m="file:"==l.location.protocol?"*":l.location.protocol+"//"+l.location.host;k=I(function(p){if(("*"==m||p.origin==m)&&p.data==n)this.port1.onmessage()},this);
l.addEventListener("message",k,!1);this.port1={};this.port2={postMessage:function(){l.postMessage(n,m)}}});if("undefined"!==typeof c&&-1==M.indexOf("Trident")&&-1==M.indexOf("MSIE")){var d=new c,e={},f=e;d.port1.onmessage=function(){if(void 0!==e.next){e=e.next;var k=e.ea;e.ea=null;k()}};return function(k){f.next={ea:k};f=f.next;d.port2.postMessage(0)}}return function(k){E.setTimeout(k,0)}};
var Yc=function(){this.h=this.g=null};Yc.prototype.add=function(c,d){var e=Zc.get();e.set(c,d);this.h?this.h.next=e:this.g=e;this.h=e};var ad=function(){var c=$c,d=null;c.g&&(d=c.g,c.g=c.g.next,c.g||(c.h=null),d.next=null);return d},Zc=new Tc(function(){return new bd},function(c){return c.reset()}),bd=function(){this.next=this.scope=this.g=null};bd.prototype.set=function(c,d){this.g=c;this.scope=d;this.next=null};bd.prototype.reset=function(){this.next=this.scope=this.g=null};
var fd=function(c,d){cd||dd();ed||(cd(),ed=!0);$c.add(c,d)},cd,dd=function(){if(E.Promise&&E.Promise.resolve){var c=E.Promise.resolve(void 0);cd=function(){c.then(gd)}}else cd=function(){var d=gd;typeof E.setImmediate!==u||E.Window&&E.Window.prototype&&-1==M.indexOf("Edge")&&E.Window.prototype.setImmediate==E.setImmediate?(Wc||(Wc=Xc()),Wc(d)):E.setImmediate(d)}},ed=!1,$c=new Yc,gd=function(){for(var c;c=ad();){try{c.g.call(c.scope)}catch(d){Qa(d)}Uc(Zc,c)}ed=!1};
var hd=function(c){if(!c)return!1;try{return!!c.$goog_Thenable}catch(d){return!1}};
var jd=function(c){this.g=0;this.o=void 0;this.j=this.h=this.i=null;this.l=this.m=!1;if(c!=Ib)try{var d=this;c.call(void 0,function(e){id(d,2,e)},function(e){id(d,3,e)})}catch(e){id(this,3,e)}},kd=function(){this.next=this.i=this.h=this.j=this.g=null;this.l=!1};kd.prototype.reset=function(){this.i=this.h=this.j=this.g=null;this.l=!1};var ld=new Tc(function(){return new kd},function(c){c.reset()}),md=function(c,d,e){var f=ld.get();f.j=c;f.h=d;f.i=e;return f};
jd.prototype.then=function(c,d,e){return nd(this,typeof c===u?c:null,typeof d===u?d:null,e)};jd.prototype.$goog_Thenable=!0;jd.prototype.cancel=function(c){if(0==this.g){var d=new od(c);fd(function(){pd(this,d)},this)}};
var pd=function(c,d){if(0==c.g)if(c.i){var e=c.i;if(e.h){for(var f=0,k=null,l=null,n=e.h;n&&(n.l||(f++,n.g==c&&(k=n),!(k&&1<f)));n=n.next)k||(l=n);k&&(0==e.g&&1==f?pd(e,d):(l?(f=l,f.next==e.j&&(e.j=f),f.next=f.next.next):qd(e),rd(e,k,3,d)))}c.i=null}else id(c,3,d)},td=function(c,d){c.h||2!=c.g&&3!=c.g||sd(c);c.j?c.j.next=d:c.h=d;c.j=d},nd=function(c,d,e,f){var k=md(null,null,null);k.g=new jd(function(l,n){k.j=d?function(m){try{var p=d.call(f,m);l(p)}catch(q){n(q)}}:l;k.h=e?function(m){try{var p=e.call(f,
m);void 0===p&&m instanceof od?n(m):l(p)}catch(q){n(q)}}:n});k.g.i=c;td(c,k);return k.g};jd.prototype.D=function(c){this.g=0;id(this,2,c)};jd.prototype.F=function(c){this.g=0;id(this,3,c)};
var id=function(c,d,e){if(0==c.g){c===e&&(d=3,e=new TypeError("m"));c.g=1;a:{var f=e,k=c.D,l=c.F;if(f instanceof jd){td(f,md(k||Ib,l||null,c));var n=!0}else if(hd(f))f.then(k,l,c),n=!0;else{if(Jb(f))try{var m=f.then;if(typeof m===u){ud(f,m,k,l,c);n=!0;break a}}catch(p){l.call(c,p);n=!0;break a}n=!1}}n||(c.o=e,c.g=d,c.i=null,sd(c),3!=d||e instanceof od||vd(c,e))}},ud=function(c,d,e,f,k){var l=!1,n=function(p){l||(l=!0,e.call(k,p))},m=function(p){l||(l=!0,f.call(k,p))};try{d.call(c,n,m)}catch(p){m(p)}},
sd=function(c){c.m||(c.m=!0,fd(c.s,c))},qd=function(c){var d=null;c.h&&(d=c.h,c.h=d.next,d.next=null);c.h||(c.j=null);return d};jd.prototype.s=function(){for(var c;c=qd(this);)rd(this,c,this.g,this.o);this.m=!1};
var rd=function(c,d,e,f){if(3==e&&d.h&&!d.l)for(;c&&c.l;c=c.i)c.l=!1;if(d.g)d.g.i=null,wd(d,e,f);else try{d.l?d.j.call(d.i):wd(d,e,f)}catch(k){xd.call(null,k)}Uc(ld,d)},wd=function(c,d,e){2==d?c.j.call(c.i,e):c.h&&c.h.call(c.i,e)},vd=function(c,d){c.l=!0;fd(function(){c.l&&xd.call(null,d)})},xd=Qa,od=function(c){H.call(this,c)};J(od,H);od.prototype.name="cancel";
/*
 Portions of this code are from MochiKit, received by
 The Closure Authors under the MIT license. All other code is Copyright
 2005-2009 The Closure Authors. All Rights Reserved.
*/
var Q=function(){this.m=[];this.l=this.j=!1;this.i=void 0;this.F=this.J=this.s=!1;this.o=0;this.h=null;this.D=0};Q.prototype.cancel=function(c){if(this.j)this.i instanceof Q&&this.i.cancel();else{if(this.h){var d=this.h;delete this.h;c?d.cancel(c):(d.D--,0>=d.D&&d.cancel())}this.F=!0;this.j||T(this,new yd(this))}};Q.prototype.H=function(c,d){this.s=!1;zd(this,c,d)};var zd=function(c,d,e){c.j=!0;c.i=e;c.l=!d;Ad(c)},Cd=function(c){if(c.j){if(!c.F)throw new Bd(c);c.F=!1}};
Q.prototype.g=function(c){Cd(this);zd(this,!0,c)};var T=function(c,d){Cd(c);zd(c,!1,d)},Ed=function(c,d){return Dd(c,d,null,void 0)},Fd=function(c,d){return Dd(c,null,d,void 0)},Dd=function(c,d,e,f){c.m.push([d,e,f]);c.j&&Ad(c);return c};Q.prototype.then=function(c,d,e){var f,k,l=new jd(function(n,m){f=n;k=m});Dd(this,f,function(n){n instanceof yd?l.cancel():k(n)});return l.then(c,d,e)};Q.prototype.$goog_Thenable=!0;
var Gd=function(c){return gc(c.m,function(d){return typeof d[1]===u})},Ad=function(c){if(c.o&&c.j&&Gd(c)){var d=c.o,e=Hd[d];e&&(E.clearTimeout(e.g),delete Hd[d]);c.o=0}c.h&&(c.h.D--,delete c.h);d=c.i;for(var f=e=!1;c.m.length&&!c.s;){var k=c.m.shift(),l=k[0],n=k[1];k=k[2];if(l=c.l?n:l)try{var m=l.call(k||null,d);void 0!==m&&(c.l=c.l&&(m==d||m instanceof Error),c.i=d=m);if(hd(d)||typeof E.Promise===u&&d instanceof E.Promise)f=!0,c.s=!0}catch(p){d=p,c.l=!0,Gd(c)||(e=!0)}}c.i=d;f&&(m=I(c.H,c,!0),f=I(c.H,
c,!1),d instanceof Q?(Dd(d,m,f),d.J=!0):d.then(m,f));e&&(d=new Id(d),Hd[d.g]=d,c.o=d.g)},Bd=function(){H.call(this)};J(Bd,H);Bd.prototype.message="Deferred has already fired";Bd.prototype.name="AlreadyCalledError";var yd=function(){H.call(this)};J(yd,H);yd.prototype.message="Deferred was canceled";yd.prototype.name="CanceledError";var Id=function(c){this.g=E.setTimeout(I(this.i,this),0);this.h=c};Id.prototype.i=function(){delete Hd[this.g];throw this.h;};var Hd={};
var Jd=function(c){this.g=c},Kd=function(c,d,e,f,k){var l=new Q;try{var n=k?c.g[d](f,k):c.g[d](f)}catch(m){return e+=pc(f),k&&(e+=", with key "+pc(k)),T(l,dc(m,e)),l}n.onsuccess=function(m){l.g(m.target.result)};n.onerror=function(m){e+=pc(f);k&&(e+=", with key "+pc(k));T(l,cc(m.target,e))};return l},Ld=function(c,d){return Kd(c,"put","putting into "+c.g.name+" with value",d,void 0)};Jd.prototype.add=function(c,d){return Kd(this,"add","adding into "+this.g.name+" with value ",c,d)};
var Md=function(c,d){var e=new Q;try{var f=c.g["delete"](d)}catch(k){f=Na+c.g.name+ra+pc(d);T(e,dc(k,f));return}f.onsuccess=function(){e.g()};f.onerror=function(k){var l=Na+c.g.name+ra+pc(d);T(e,cc(k.target,l))}};Jd.prototype.get=function(c){var d=new Q;try{var e=this.g.get(c)}catch(k){return e="getting from "+this.g.name+ra+pc(c),T(d,dc(k,e)),d}e.onsuccess=function(k){d.g(k.target.result)};var f=this;e.onerror=function(k){var l="getting from "+f.g.name+ra+pc(c);T(d,cc(k.target,l))};return d};
var Nd=function(c,d){var e=new Q;try{var f=c.g.getAll(void 0,void 0)}catch(k){return d+=qa,T(e,dc(k,d)),e}f.onsuccess=function(){e.g(f.result)};f.onerror=function(k){d+=qa;T(e,cc(k.target,d))};return e};Jd.prototype.clear=function(){var c="clearing store "+this.g.name,d=new Q;try{var e=this.g.clear()}catch(f){return T(d,dc(f,c)),d}e.onsuccess=function(){d.g()};e.onerror=function(f){T(d,cc(f.target,c))};return d};
var Od=function(c){this.h=c;this.g={}};J(Od,qc);var Pd=[];Od.prototype.B=function(c,d,e,f){Array.isArray(d)||(d&&(Pd[0]=d.toString()),d=Pd);for(var k=0;k<d.length;k++){var l=Ra(c,d[k],e||this.handleEvent,f||!1,this.h||this);if(!l)break;this.g[l.key]=l}return this};Od.prototype.ja=function(c,d,e,f){return Qd(this,c,d,e,f)};var Qd=function(c,d,e,f,k,l){if(Array.isArray(e))for(var n=0;n<e.length;n++)Qd(c,d,e[n],f,k,l);else{d=Hc(d,e,f||c.handleEvent,k,l||c.h||c);if(!d)return c;c.g[d.key]=d}return c};
Od.prototype.da=function(c,d,e,f,k){if(Array.isArray(d))for(var l=0;l<d.length;l++)this.da(c,d[l],e,f,k);else e=e||this.handleEvent,f=Jb(f)?!!f.capture:!!f,k=k||this.h||this,e=Ic(e),f=!!f,d=xc(c)?c.L(d,e,f,k):c?(c=Kc(c))?c.L(d,e,f,k):null:null,d&&(Pc(d),delete this.g[d.key])};Od.prototype.handleEvent=function(){throw Error("n");};
var Rd=function(c,d){Rc.call(this);this.g=c;this.j=d;this.i=new Od(this);this.i.B(this.g,Ea,I(this.dispatchEvent,this,Ea));this.i.B(this.g,Da,I(this.dispatchEvent,this,Da));this.i.B(this.g,Ha,this.ra)};J(Rd,Rc);w=Rd.prototype;w.ra=function(c){c.target instanceof Rb?this.dispatchEvent({type:Ha,target:c.target}):this.dispatchEvent({type:Ha,target:cc(c.target,"in transaction")})};w.objectStore=function(c){try{return new Jd(this.g.objectStore(c))}catch(d){throw dc(d,"getting object store "+c);}};
w.commit=function(c){if(this.g.commit||!c)try{this.g.commit()}catch(d){throw dc(d,"cannot commit the transaction");}};w.wait=function(){var c=new Q;Hc(this,Ea,I(c.g,c));var d=Hc(this,Da,function(){Pc(e);T(c,new Rb(Xb,"waiting for transaction to complete"))});var e=Hc(this,Ha,function(k){Pc(d);T(c,k.target)});var f=this.j;return Ed(c,function(){return f})};w.abort=function(){this.g.abort()};
var Sd=function(c){Rc.call(this);this.g=c;this.i=new Od(this);this.i.B(this.g,Da,I(this.dispatchEvent,this,Da));this.i.B(this.g,Ha,this.l);this.i.B(this.g,"versionchange",this.o);this.i.B(this.g,"close",I(this.dispatchEvent,this,"close"))};J(Sd,Rc);Sd.prototype.j=!0;Sd.prototype.l=function(c){c=(c=c.target)&&c.error;this.dispatchEvent({type:Ha,errorCode:c&&c.severity})};Sd.prototype.o=function(c){this.dispatchEvent(new Td(c.oldVersion,c.newVersion))};
Sd.prototype.close=function(){this.j&&(this.g.close(),this.j=!1)};var Ud=function(c,d,e){try{c.g.createObjectStore(d,e)}catch(f){throw dc(f,"creating object store "+d);}},Vd=function(c,d){try{var e=c.g.transaction(d,Ma);return new Rd(e,c)}catch(f){throw dc(f,"creating transaction");}},Td=function(c,d){rc.call(this,"versionchange");this.oldVersion=c;this.newVersion=d};J(Td,rc);
var Wd=function(){void 0==Ob&&(Ob=E.indexedDB||E.mozIndexedDB||E.webkitIndexedDB||E.moz_indexedDB);return Ob},Xd=function(c,d,e){var f=new Q;d=d?Wd().open(c,d):Wd().open(c);d.onsuccess=function(k){k=new Sd(k.target.result);f.g(k)};d.onerror=function(k){T(f,cc(k.target,"opening database "+c))};d.onupgradeneeded=function(k){if(e){var l=new Sd(k.target.result);e(new Td(k.oldVersion,k.newVersion),l,new Rd(k.target.transaction,l))}};d.onblocked=v();return f};
var Zd=function(c,d,e,f){e=void 0===e?{}:e;f=void 0===f?{}:f;this.url=c;this.i=void 0===d?0:d;this.h=e;this.g=f;this.keyPath=Yd()+"::"+c},Yd=da("StoredCacheHitCounters"),$d=function(c){if(c&&c.url&&typeof c.url===F&&typeof c.hits===La){var d;if(Jb(c.misses)){var e=c.misses;Object.keys(e).every(function(l){return typeof l===F&&typeof e[l]===La})&&(d=e)}var f;if(Jb(c.changes)){var k=c.changes;Object.keys(k).every(function(l){return typeof l===F&&typeof k[l]===La})&&(f=k)}return new Zd(c.url,c.hits,
d,f)}},ae=function(c){var d={url:c.url,hits:c.i,keyPath:c.keyPath};c.h&&Object.keys(c.h).length&&(d.misses=c.h);c.g&&Object.keys(c.g).length&&(d.changes=c.g);return d},db=function(c,d,e,f){this.scope=c;this.g=d;this.reason=e;this.time=f;this.keyPath=Za()+"::"+c},Za=da("StoredCacheState"),ab=function(c){return{scope:c.scope,isEmpty:c.g,reason:c.reason,time:c.time.toDateString(),keyPath:c.keyPath}},$a=function(c){if(c&&typeof c.scope===F&&"boolean"===typeof c.isEmpty&&typeof c.reason===F&&Date.parse(c.time))return new db(c.scope,
c.isEmpty,c.reason,new Date(c.time))},Ya=function(c){this.g=c;this.h=be()},ce=da("gmail-sw-keyval-objects"),be=function(){return Promise.resolve(Xd("gmail-sw-keyval",2,function(c,d){if((c=d.g.objectStoreNames)&&c.contains(ce())){c=ce();try{d.g.deleteObjectStore(c)}catch(e){throw dc(e,"deleting object store "+c);}}Ud(d,ce(),{keyPath:"keyPath"})}))};Ya.prototype.get=function(c){var d=this;return de(this,function(e){return e.get(d.g.$()+"::"+c)}).then(function(e){return d.g.parse(e)})};
var cb=function(c,d,e){return de(c,function(f){return new Promise(function(k,l){return Fd(Ed(f.get(c.g.$()+"::"+d),function(n){return k(Ld(f,c.g.la(e(c.g.parse(n)))))}),function(n){return l(n)})})})},bb=function(c){return c.h.then(function(d){var e=Vd(d,[ce()]).objectStore(ce());return new Promise(function(f,k){return Fd(Ed(Nd(e,"getting all from index "+e.g.name),function(l){f(l.filter(function(n){return n.keyPath&&n.keyPath.startsWith(c.g.$()+"::")}).map(function(n){Md(e,n.keyPath);return c.g.parse(n)}).filter(function(n){return!!n}))}),
function(l){return k(l)})})})};Ya.prototype.clear=function(){return de(this,function(c){return c.clear()})};var de=function(c,d){return c.h.then(function(e){e=Vd(e,[ce()]);var f=e.objectStore(ce());return Sa(e,d(f))})};
var Wa=function(){this.g=new Ya({$:Yd,parse:$d,la:ae})},ee=function(c,d){cb(c.g,d,function(e){e=e||new Zd(d);e.i++;return e})},fe=function(c,d,e){cb(c.g,d,function(f){f=f||new Zd(d);f.h[e]?f.h[e]++:f.h[e]=1;return f})},Xa=function(c,d){cb(c.g,d,function(e){e=e||new Zd(d);e.g.quota_exceeded?e.g.quota_exceeded++:e.g.quota_exceeded=1;return e})};Wa.prototype.get=function(c){return this.g.get(c)};
var lb=new Set(["auth","hl","zx","tab","ui","authuser","tz","pli","shva","ibxr",Ga,"features","jsmode","labs","traceDebugger","ddpk","ogbl"]);
var ge=function(c,d){this.h={};this.g=[];this.i=0;var e=arguments.length;if(1<e){if(e%2)throw Error("o");for(var f=0;f<e;f+=2)this.set(arguments[f],arguments[f+1])}else if(c)if(c instanceof ge)for(e=c.I(),f=0;f<e.length;f++)this.set(e[f],c.get(e[f]));else for(f in c)this.set(f,c[f])};ge.prototype.M=function(){he(this);for(var c=[],d=0;d<this.g.length;d++)c.push(this.h[this.g[d]]);return c};ge.prototype.I=function(){he(this);return this.g.concat()};
ge.prototype.clear=function(){this.h={};this.i=this.g.length=0};var he=function(c){if(c.i!=c.g.length){for(var d=0,e=0;d<c.g.length;){var f=c.g[d];ie(c.h,f)&&(c.g[e++]=f);d++}c.g.length=e}if(c.i!=c.g.length){var k={};for(e=d=0;d<c.g.length;)f=c.g[d],ie(k,f)||(c.g[e++]=f,k[f]=1),d++;c.g.length=e}};ge.prototype.get=function(c,d){return ie(this.h,c)?this.h[c]:d};ge.prototype.set=function(c,d){ie(this.h,c)||(this.i++,this.g.push(c));this.h[c]=d};
ge.prototype.forEach=function(c,d){for(var e=this.I(),f=0;f<e.length;f++){var k=e[f],l=this.get(k);c.call(d,l,k,this)}};var ie=function(c,d){return Object.prototype.hasOwnProperty.call(c,d)};
var je=/^(?:([^:/?#.]+):)?(?:\/\/(?:([^\\/?#]*)@)?([^\\/?#]*?)(?::([0-9]+))?(?=[\\/?#]|$))?([^?#]+)?(?:\?([^#]*))?(?:#([\s\S]*))?$/,ke=function(c,d){if(c){c=c.split("&");for(var e=0;e<c.length;e++){var f=c[e].indexOf("="),k=null;if(0<=f){var l=c[e].substring(0,f);k=c[e].substring(f+1)}else l=c[e];d(l,k?decodeURIComponent(k.replace(/\+/g," ")):"")}}},le=function(c,d,e){if(Array.isArray(d))for(var f=0;f<d.length;f++)le(c,String(d[f]),e);else null!=d&&e.push(c+(""===d?"":"="+encodeURIComponent(String(d))))},
me=function(c){var d=[],e;for(e in c)le(e,c[e],d);return d.join("&")};
var ne=function(c,d){this.i=this.o=this.j="";this.s=null;this.m=this.g="";this.l=!1;var e;c instanceof ne?(this.l=void 0!==d?d:c.l,oe(this,c.j),this.o=c.o,this.i=c.i,pe(this,c.s),this.g=c.g,qe(this,re(c.h)),this.m=c.m):c&&(e=String(c).match(je))?(this.l=!!d,oe(this,e[1]||"",!0),this.o=se(e[2]||""),this.i=se(e[3]||"",!0),pe(this,e[4]),this.g=se(e[5]||"",!0),qe(this,e[6]||"",!0),this.m=se(e[7]||"")):(this.l=!!d,this.h=new te(null,this.l))};
ne.prototype.toString=function(){var c=[],d=this.j;d&&c.push(ue(d,ve,!0),":");var e=this.i;if(e||"file"==d)c.push("//"),(d=this.o)&&c.push(ue(d,ve,!0),"@"),c.push(encodeURIComponent(String(e)).replace(/%25([0-9a-fA-F]{2})/g,"%$1")),e=this.s,null!=e&&c.push(":",String(e));if(e=this.g)this.i&&"/"!=e.charAt(0)&&c.push("/"),c.push(ue(e,"/"==e.charAt(0)?we:xe,!0));(e=this.h.toString())&&c.push("?",e);(e=this.m)&&c.push("#",ue(e,ye));return c.join("")};
ne.prototype.resolve=function(c){var d=new ne(this),e=!!c.j;e?oe(d,c.j):e=!!c.o;e?d.o=c.o:e=!!c.i;e?d.i=c.i:e=null!=c.s;var f=c.g;if(e)pe(d,c.s);else if(e=!!c.g){if("/"!=f.charAt(0))if(this.i&&!this.g)f="/"+f;else{var k=d.g.lastIndexOf("/");-1!=k&&(f=d.g.substr(0,k+1)+f)}k=f;if(".."==k||"."==k)f="";else if(-1!=k.indexOf("./")||-1!=k.indexOf("/.")){f=0==k.lastIndexOf("/",0);k=k.split("/");for(var l=[],n=0;n<k.length;){var m=k[n++];"."==m?f&&n==k.length&&l.push(""):".."==m?((1<l.length||1==l.length&&
""!=l[0])&&l.pop(),f&&n==k.length&&l.push("")):(l.push(m),f=!0)}f=l.join("/")}else f=k}e?d.g=f:e=""!==c.h.toString();e?qe(d,re(c.h)):e=!!c.m;e&&(d.m=c.m);return d};
var oe=function(c,d,e){c.j=e?se(d,!0):d;c.j&&(c.j=c.j.replace(/:$/,""))},pe=function(c,d){if(d){d=Number(d);if(isNaN(d)||0>d)throw Error("p`"+d);c.s=d}else c.s=null},qe=function(c,d,e){d instanceof te?(c.h=d,ze(c.h,c.l)):(e||(d=ue(d,Ae)),c.h=new te(d,c.l))},ob=function(c){return c instanceof ne?new ne(c):new ne(c,void 0)},se=function(c,d){return c?d?decodeURI(c.replace(/%25/g,"%2525")):decodeURIComponent(c):""},ue=function(c,d,e){return typeof c===F?(c=encodeURI(c).replace(d,Be),e&&(c=c.replace(/%25([0-9a-fA-F]{2})/g,
"%$1")),c):null},Be=function(c){c=c.charCodeAt(0);return"%"+(c>>4&15).toString(16)+(c&15).toString(16)},ve=/[#\/\?@]/g,xe=/[#\?:]/g,we=/[#\?]/g,Ae=/[#\?@]/g,ye=/#/g,te=function(c,d){this.h=this.g=null;this.i=c||null;this.j=!!d},Ce=function(c){c.g||(c.g=new ge,c.h=0,c.i&&ke(c.i,function(d,e){c.add(decodeURIComponent(d.replace(/\+/g," ")),e)}))};te.prototype.add=function(c,d){Ce(this);this.i=null;c=De(this,c);var e=this.g.get(c);e||this.g.set(c,e=[]);e.push(d);this.h+=1;return this};
var qb=function(c,d){Ce(c);d=De(c,d);ie(c.g.h,d)&&(c.i=null,c.h-=c.g.get(d).length,c=c.g,ie(c.h,d)&&(delete c.h[d],c.i--,c.g.length>2*c.i&&he(c)))};te.prototype.clear=function(){this.g=this.i=null;this.h=0};var Ee=function(c,d){Ce(c);d=De(c,d);return ie(c.g.h,d)};w=te.prototype;w.forEach=function(c,d){Ce(this);this.g.forEach(function(e,f){fc(e,function(k){c.call(d,k,f,this)},this)},this)};
w.I=function(){Ce(this);for(var c=this.g.M(),d=this.g.I(),e=[],f=0;f<d.length;f++)for(var k=c[f],l=0;l<k.length;l++)e.push(d[f]);return e};w.M=function(c){Ce(this);var d=[];if(typeof c===F)Ee(this,c)&&(d=Pa(d,this.g.get(De(this,c))));else{c=this.g.M();for(var e=0;e<c.length;e++)d=Pa(d,c[e])}return d};w.set=function(c,d){Ce(this);this.i=null;c=De(this,c);Ee(this,c)&&(this.h-=this.g.get(c).length);this.g.set(c,[d]);this.h+=1;return this};
w.get=function(c,d){if(!c)return d;c=this.M(c);return 0<c.length?String(c[0]):d};w.toString=function(){if(this.i)return this.i;if(!this.g)return"";for(var c=[],d=this.g.I(),e=0;e<d.length;e++){var f=d[e],k=encodeURIComponent(String(f));f=this.M(f);for(var l=0;l<f.length;l++){var n=k;""!==f[l]&&(n+="="+encodeURIComponent(String(f[l])));c.push(n)}}return this.i=c.join("&")};
var re=function(c){var d=new te;d.i=c.i;c.g&&(d.g=new ge(c.g),d.h=c.h);return d},De=function(c,d){d=String(d);c.j&&(d=d.toLowerCase());return d},ze=function(c,d){d&&!c.j&&(Ce(c),c.i=null,c.g.forEach(function(e,f){var k=f.toLowerCase();if(f!=k&&(qb(this,f),qb(this,k),0<e.length)){this.i=null;f=this.g;var l=f.set;k=De(this,k);var n=e.length;if(0<n){for(var m=Array(n),p=0;p<n;p++)m[p]=e[p];n=m}else n=[];l.call(f,k,n);this.h+=e.length}},c));c.j=d};
var hb=/^\/mail\/(ca\/)?(u\/\d+\/)?$/,ib=/\/mail(\/ca)?\/b\/[^\/]+\/u\/[^\/]+/,jb=/\/a\/[^\/]+\/b\/[^\/]+\/u\/[^\/]+/,pb=new Set(["zx","tab","pli","shva","ibxr",Ga,"ddpk","ogbl"]),sb=/^\/chat\/(u\/\d+\/)?$/,tb=/^\/mail\/(ca\/)?(u\/\d+\/)?chat\/$/;
var Ge=function(){this.g=Fe.caches},Ie=function(c,d){return He(c,d).then(function(e){if(e){var f=new URL(d.url);if(f.searchParams){var k=f.searchParams.get("disp");f="att"==f.searchParams.get("view")&&("safe"==k||"attd"==k||"zip"==k||"inzip"==k)}else f=!1;return f?(e.headers.get(ua)||(f="attachment",(k=e.headers.get("fileNameForDownload"))&&(f+="; filename="+k),e.headers.append(ua,f)),e.headers.append("Content-Security-Policy","default-src none"),e.headers.get(Aa)||e.headers.append(Aa,"nosniff"),
Promise.resolve(e)):e}return fetch(d)})},He=function(c,d){d=(new URL(d.url)).searchParams;var e=[];d.get("permmsgid")?e.push("permmsgid="+d.get("permmsgid")):d.get("th")&&e.push("th="+d.get("th"));e.push("attid="+d.get("attid"));d.get("realattid")&&e.push("realattid="+d.get("realattid"));return c.g.match(e.join("&"))};
var Je=function(){this.g={};this.i="";this.h={}};
Je.prototype.toString=function(){if("1"==U(this,"md"))return Ke(this);var c=[],d=I(function(f){void 0!==this.g[f]&&c.push(f+"="+this.g[f])},this);d("sdch");d("k");d("ck");d("am");d("rt");"d"in this.g||(this.g.d="0");d("d");d("exm");d("excm");(this.g.excm||this.g.exm)&&c.push("ed=1");d("dg");"1"==U(this,"br")&&d("br");a:switch(U(this,"wt")){case "0":var e="0";break a;case "2":e="2";break a;default:e="1"}"1"!==e&&d("wt");d("sm");d("im");a:switch(U(this,"ct")){case "zgms":e="zgms";break a;default:e=
"gms"}"zgms"==e&&d("ct");d("rs");d("ee");d(Fa);d("m");d("cb");d=me(this.h);e="";""!=d&&(e="?"+d);return this.i+c.join("/")+e};
var Ke=function(c){var d=[],e=I(function(k){void 0!==this.g[k]&&d.push(k+"="+this.g[k])},c);e("md");e("k");e("ck");e("ct");e("am");e("rs");e(Fa);e=me(c.h);var f="";""!=e&&(f="?"+e);return c.i+d.join("/")+f},U=function(c,d){return c.g[d]?c.g[d]:null},Le=function(c){return(c=U(c,"exm"))?c.split(","):[]},Me=function(c){return(c=U(c,"m"))?c.split(","):[]},Ne=function(c){var d=U(c,"ee");if(!d)return{};c={};d=B(d.split(";"));for(var e=d.next();!e.done;e=d.next()){var f=B(e.value.split(":"));e=f.next().value;
f=f.next().value;c[e]={};f=B(f.split(","));for(var k=f.next();!k.done;k=f.next())c[e][k.value]=!0}return c},Oe=function(c){var d=void 0===d?!0:d;var e=c.startsWith("https://uberproxy-pen-redirect.corp.google.com/uberproxy/pen?url=")?c.substr(65):c,f=new Je,k=e.match(je)[5];kc(function(n){var m=k.match("/"+n+"=([^/]+)");m&&((m=m[1])?f.g[n]=m:delete f.g[n])});var l=-1!=c.indexOf("_/ss/")?"_/ss/":"_/js/";f.i=c.substr(0,c.indexOf(l)+l.length);if(!d)return f;(c=e.match(je)[6]||null)&&ke(c,function(n,m){f.h[n]=
m});return f},Pe=function(c){c=(c=c.match(je)[5]||null)?decodeURI(c):c;return null!==c&&!!c.match("(/_/js/)|(/_/ss/)")&&!!c.match("/k=")},jc={Ra:"k",Aa:"ck",Na:"m",Ia:"exm",Ga:"excm",ya:"am",Qa:"rt",Ka:"d",Ha:"ed",Va:"sv",Da:"deob",za:"cb",Ta:"rs",Sa:"sdch",La:"im",Ea:"dg",Fa:"br",Xa:"wt",Ja:"ee",Ua:"sm",Ma:"md",Ba:"ct",Ca:Fa};
var Qe=self;
var Re=function(c,d){this.j=void 0===c?!0:c;this.ba=new Map;this.ca=[];this.ha=!1;this.g="";this.h=!1;this.i={};this.ka={};this.ga=this.fa=void 0;this.ia="";this.xa=void 0===d?!1:d},Se=function(c,d){var e=new Map,f=[];d=B(d.split("/"));for(var k=d.next();!k.done;k=d.next()){var l=B(k.value.split(":"));k=l.next().value;var n=l.next().value;l=[];if(n){n=B(n.split(","));for(var m=n.next();!m.done;m=n.next())l.push(f[parseInt(m.value,36)])}e.set(k,l);f.push(k)}c.ba=e;c.ca=f;c.ha=!0},Ue=function(c,d){c.g+=
d;d=/\/\*(?: _Global|_M:|_CSS\*\/|_JS\*\/)/g;var e;if(e=d.exec(c.g)){for(var f=e.index;e=d.exec(c.g);)e=e.index,Te(c,c.g.slice(f,e)),f=e;c.g=c.g.slice(f)}},Te=function(c,d){if(/^\/\* _GlobalPrefix_ \*\//.test(d))c.fa=d;else if(/^\/\* _GlobalSuffix_ \*\//.test(d))c.ga=d;else if(/^\/\*_CSS\*\//.test(d))c.h=!0;else if(/^\/\*_JS\*\//.test(d))c.h=!1,c.ia=d;else{var e=/^\/\*_M:([\w\-\*]+) ?\*\//.exec(d);null!=e&&(e=e[1],c.h?c.i[e]=d:c.ka[e]=d,c.j&&c.ba&&(d=/(?:_ModuleManager_initialize|\(0,_._ModuleManager_initialize\))\('([\w\-\*,:\/]+)'/.exec(d),
null!=d&&Se(c,d[1])))}},Ve=function(c,d){if(!c.ok)return Promise.reject(Error("r"));if(!d&&!Pe(c.url))return Promise.reject(Error("s"));d=d||Oe(c.url);if("1"==U(d,"md"))return c.json().then(function(m){var p=new Re(!1,!0);Se(p,m.moduleGraph);return p});a:switch(U(d,"dg")){case "0":var e="0";break a;case "2":e="2";break a;default:e="1"}var f=new Re("1"==e&&0==Le(d).length,!1);if(!c.body)return c.text().then(function(m){Ue(f,m);Te(f,f.g);return f});var k=new TextDecoder,l=c.body.getReader(),n=function(){return l.read().then(function(m){if(m=
m.value)return m=k.decode(m,{stream:!0}),Ue(f,m),n();Te(f,f.g);return f})};return n()};
var We=function(){this.rootModule=this.moduleGraph=this.suffix=this.jsSectionPrefix=this.prefix=null;this.storedModules=new Set;this.lastUseMs=Date.now()},Xe=function(c){this.h=c;this.g=null},Ze=function(c,d,e,f){return(c.g||Ye(c)).then(function(k){k=k.transaction([Ja,Oa],Ma);for(var l=k.objectStore(Ja),n=k.objectStore(Oa),m=B(e.keys()),p=m.next();!p.done;p=m.next()){p=p.value;var q={};l.put((q.content=e.get(p),q),d+";"+p)}n.put(f,d);return Bb(k)})},$e=function(c,d,e){var f=[].concat(Hb(e)).sort(),
k=0,l=new Map;return new Promise(function(n,m){var p=setTimeout(function(){n(null)},5E3);(c.g||Ye(c)).then(function(q){var r=q.transaction([Ja],"readonly");r.objectStore(Ja).openCursor(IDBKeyRange.bound(d,d+String.fromCharCode(60))).onsuccess=function(x){x=x.target.result;if(!x)n(null);else if(x){var D=x.key.split(";")[1],W=f[k];D>W?n(null):(D==W&&(l.set(D,x.value.content),++k),e.length==l.size?n(l):k<f.length&&x.continue(d+";"+f[k]))}};r.onerror=function(){m(r.error)}}).finally(function(){clearTimeout(p)})})},
af=function(c,d){return(c.g||Ye(c)).then(function(e){e=e.transaction([Oa],"readonly").objectStore(Oa).get(d);return Ab(e)})};Xe.prototype.clear=function(){return(this.g||Ye(this)).then(function(c){c=c.transaction([Ja,Oa],Ma);c.objectStore(Ja).clear();c.objectStore(Oa).clear();return Bb(c)})};
var Ye=function(c){var d=Qe.indexedDB.open(c.h,1);d.onupgradeneeded=zb;d.onblocked=v();c.g=Ab(d);c.g.then(function(e){return bf(c,e)});return c.g},bf=function(c,d){d.onversionchange=function(e){e.newVersion||(d.close(),c.g=null)}};
var Cb=null,Eb=null,Fb=/((?:_ModuleManager_initialize|\(0,_._ModuleManager_initialize\))\('[\w\-\*,:\/]+'\s*,\s*\[)[\w'"*,\s]+(\]\s*?\))/g,cf=function(c){this.g=new Xe(c)};cf.prototype.clear=function(){return this.g.clear()};
var ef=function(c,d,e){var f=0;f=void 0===f?0:f;var k=U(d,"k")+"."+U(d,"am");return Promise.all([Ve(e,d),df(c,k)]).then(function(l){var n=B(l);l=n.next().value;var m=n.next().value;m.lastUseMs=Date.now();n=l.xa;var p=new Map;if(n||l.ha)m.moduleGraph=l.ba,m.rootModule=l.ca&&l.ca[0];if(!n){m.prefix=Db(l.fa);m.jsSectionPrefix=Db(l.ia);m.suffix=Db(l.ga);l=l.ka;for(var q in l)q in m.storedModules||p.set(q,Db(l[q]));m.storedModules=new Set([].concat(Hb(m.storedModules),Hb(p.keys())))}return new Promise(function(r,
x){setTimeout(function(){Ze(c.g,k,p,m).then(r,x)},f)})})},df=function(c,d){return af(c.g,d).then(function(e){return e?e:new We})},gf=function(c,d){if("1"==U(c,"d")){if(!d)return null;var e=d.moduleGraph,f=d.rootModule;if(e&&f){var k=ff(Me(c),e,Ne(c));if(k){e="1"==U(c,"ed")?new Set(ff(Le(c),e,Ne(c))):new Set(Le(c));d=[];"1"==U(c,"d")&&0==e.size&&k[0]!==f&&k.unshift(f);c=B(k);for(f=c.next();!f.done;f=c.next())f=f.value,e.has(f)||d.push(f);e=d}else e=null}else e=null;return e}return Me(c)},hf=function(c,
d,e,f){if(d){if(!d.prefix||!d.suffix||!d.jsSectionPrefix)return null;for(var k=d.storedModules,l=B(Me(e)),n=l.next();!n.done;n=l.next())if(!k.has(n.value))return null}var m=gf(e,d);return m?Promise.all([d||df(c,f),$e(c.g,f,m)]).then(function(p){var q=B(p);p=q.next().value;var r=q.next().value;if(r&&m){q=p.prefix;var x=p.jsSectionPrefix,D=p.suffix;p=Gb(r,m,p.rootModule);return new Response(new Blob([q,x].concat(Hb(p),[D])))}return null}):null},ff=function(c,d,e){var f=[],k=new Set;c=B(c);for(var l=
c.next();!l.done;l=c.next())if(1!==jf(l.value,d,e,new Set,k,f))return null;return f},jf=function(c,d,e,f,k,l){if(k.has(c))return 1;if(f.has(c))return 2;f.add(c);if(d.has(c))for(var n=B(d.get(c)),m=n.next();!m.done;m=n.next())if(m=jf(m.value,d,e,f,k,l),1!==m)return m;if(e.hasOwnProperty(c))for(n=B(Object.keys(e[c])),m=n.next();!m.done;m=n.next())if(m=jf(m.value,d,e,f,k,l),1!==m)return m;l.push(c);k.add(c);return 1};
var nf=function(){var c=Fe.caches,d=kf(lf),e=mf;this.h=c;this.l=d;this.g=e;this.i=void 0;this.m="gmail-sw-modules-"+e},pf=function(c,d){var e=(new Date).getTime();return c.h.match(rb(d.url)).then(function(f){return of(c,f,d,e)})},of=function(c,d,e,f){if(d){var k="unknown",l=!1,n=new URL(d.url);gb(n,c.g)?yb(d)?l=!0:k=Ia:fb(n)?vb(f,e,d)?l=!0:k=Ia:k="match_bad_url";return l?{v:!0,response:d}:{v:!1,reason:Promise.resolve(k)}}d=new URL(e.url);return gb(d,c.g)?{v:!1,reason:c.h.match(rb(e.url),{ignoreSearch:!0}).then(function(m){return m?
"no_match_changed_query":Ka})}:{v:!1,reason:Promise.resolve("unknown")}},rf=function(c,d){var e=eb(new URL(d.url),c.g);return e&&"js"==e.type?qf(c,d).catch(function(){return{v:!1,reason:Promise.resolve("module_set_cache_error")}}):Promise.resolve({v:!1,reason:Promise.resolve(Ka)})},sf=function(c,d,e){c.h.open("sw-"+c.g).then(function(f){f.put(rb(d.url),e)}).catch(c.j.bind(c)).then(function(){return Ua(c.g,"fetch_new_app_shell",!1)})},qf=function(c,d){var e=Oe(d.url),f=U(e,"k")+"."+U(e,"am"),k=tf(c);
return df(k,f).then(function(l){return(l=hf(k,l,e,f))?l.then(function(n){return n?{v:!0,response:n}:{v:!1,reason:Promise.resolve(Ka)}}):{v:!1,reason:Promise.resolve(Ka)}})},vf=function(c,d,e){var f=eb(new URL(d.url),c.g);f?uf(c,f,d,e).then(function(){if("js"==f.type&&c.l){var k=Oe(d.url);k=ef(tf(c),k,e)}else k=Promise.resolve();return k}):Promise.resolve()},uf=function(c,d,e,f){return c.h.open(d.name).then(function(k){return k.put(rb(e.url),f.clone())}).then(v()).catch(c.j.bind(c)).then(v())},tf=
function(c){c.i||(c.i=new cf(c.m));return c.i};nf.prototype.j=function(c){return this.l?Promise.resolve(0):c instanceof DOMException?Va():Promise.resolve(0)};
var kf=function(c){return!!c.g&&"1"==c.g.get("offline")&&"1"==c.g.get("offline_allowed")};
var wf=new Set("a b it m m_i spit l sps t".split(" ")),zf=function(c,d,e){if(!d.request||!d.request.url)throw Error("v");return e&&("only-if-cached"===d.request.cache?"same-origin"!==d.request.mode:1)?xf(c,d.request).then(function(f){return f?f:yf(c,d.request)},function(){return yf(c,d.request)}):yf(c,d.request)},xf=function(c,d){var e=new URL(d.url);return pf(c.g,d).then(function(f){mb(ob(e))&&(c.i.g=[],Af(c.i,d.url));if(f.v)return f=f.response,d.headers.get(Ca)||(ee(c.j,d.url),c.h.g.set(d.url,1)),
f;d.headers.get(Ca)||f.reason.then(function(k){fe(c.j,d.url,k);c.h.g.set(d.url,0)});return kf(c.l)?rf(c.g,d).then(function(k){return k.v?k.response:null}):null})},yf=function(c,d){return fetch(d).then(function(e){a:{var f=d.url;if(Pe(d.url)){f=Me(Oe(f));f=B(f);for(var k=f.next();!k.done;k=f.next())if(wf.has(k.value)){f=!0;break a}}f=!1}if(!f){f=c.g;k=e.clone();var l=new URL(d.url),n=new URL(k.url),m=new URL(k.url);if(gb(l,f.g)&&gb(m,f.g)&&200==k.status&&k.headers.get(Ba))sf(f,d,k);else{if(l=fb(l)&&
fb(n))if(200!=k.status)l=!1;else if(m=k.headers.get(sa)){l=!1;n=!0;m=B(m.split(","));for(var p=m.next();!p.done;p=m.next())if(p=p.value.trim(),"public"==p&&(l=!0),"no-store"==p||"no-cache"==p||"private"==p)n=!1;l=n&&l}else l=!1;l?vf(f,d,k):Promise.resolve()}}return e},function(e){throw e;})};
var Bf=function(c,d){return c.g.has(d)?{wa:c.g.get(d)}:{wa:-1}};
var Df=function(){this.g=Cf()},Ef=da("locks-object-store"),Cf=function(){return Promise.resolve(Xd("gmail-sw-locks",1,function(c,d){Ud(d,Ef(),{keyPath:"lockId"})})).catch(v())},Ff=function(c,d){return new Promise(function(e,f){return Fd(Ed(c.objectStore(Ef()).get(d),function(k){return e(k)}),function(k){return f(k)})})},Gf=function(c,d,e){var f={lockId:d,clientId:e};return new Promise(function(k,l){return Fd(Ed(Ld(c.objectStore(Ef()),f),function(){return k()}),function(n){return l(n)})})};
Df.prototype.clear=function(){return this.g.then(function(c){return Vd(c,[Ef()]).objectStore(Ef()).clear()})};
var Hf=function(){this.g=new Df},Jf=function(c,d){if(d.ports&&d.ports.length&&d.ports[0]){var e=d.ports[0];if(d.data.params&&d.data.params.lockId&&d.source&&d.source.id){var f=d.data.params.fullResult;If(c,d.data.params.lockId,d.source.id).then(function(k){f?e.postMessage({resultCode:k}):e.postMessage(1==k);return k},function(k){e.postMessage({error:k})})}else e.postMessage({error:"Got a message event with incomplete request, ignoring."}),Promise.resolve(0)}else Promise.resolve(0)},If=function(c,
d,e){return c.g.g.then(function(f){if(!f)throw Error("w");var k=Vd(f,[Ef()]);return Ff(k,d).then(function(l){return l?Kf(l,e,f):Gf(k,d,e).then(function(){return Sa(k,1)})})})},Kf=function(c,d,e){return self.clients.get(c.clientId).then(function(f){if(f)return f.id==d?Promise.resolve(1):Promise.resolve(2);var k=Vd(e,[Ef()]);return Ff(k,c.lockId).then(function(l){return l&&c.clientId!=l.clientId?Promise.resolve(2):Gf(k,c.lockId,d).then(function(){return Sa(k,1)})})})};
var Lf=function(){this.g=Fe.caches},Mf=function(c,d){return c.g.match(d).then(function(e){return e?e:fetch(d).then(function(f){return f&&"opaque"!=f.type&&!f.ok?f.clone().text().then(function(){return f}):f}).catch(v())})};
var Af=function(c,d){c.g.push({$a:"AppShellLookUp",endTime:(new Date).getTime(),Za:void 0===d?null:d})};
var Qf=function(){var c=lf,d=Nf,e=Of,f=Pf,k=new Ge,l=new Lf;this.g=Fe;this.j=c;this.h=d;this.l=e;this.J=new URL(this.g.registration.scope);this.s=kb(this.J);this.i=f;this.o=k;this.aa=l};Qf.prototype.D=function(c){this.g.registration.navigationPreload&&c.waitUntil(this.g.registration.navigationPreload.disable())};Qf.prototype.H=function(c){c.waitUntil(this.g.skipWaiting().then(da(null)))};
Qf.prototype.F=function(c){var d=new URL(c.request.url),e;if(e=!(d.searchParams.has("sw")&&"2"==d.searchParams.get("sw")))e=!(!this.s&&(kb(d)||c.request.referrer&&kb(new URL(c.request.referrer))));if(e){if(kf(this.j)){if(d.searchParams&&d.searchParams.has("th")&&d.searchParams.has("attid")&&(!d.searchParams.has("view")||"snatt"!=d.searchParams.get("view"))){c.respondWith(Ie(this.o,c.request));return}if(d.hostname.endsWith(".gstatic.com")&&(d.pathname.endsWith(".png")||d.pathname.endsWith(".gif")||
d.pathname.endsWith(".cur"))){c.respondWith(Mf(this.aa,c.request));return}}(d=fb(d)||gb(d,this.i.m)&&!(d.searchParams&&"0"==d.searchParams.get("sw_cache")))&&c.respondWith(zf(this.i,c,d))}};
Qf.prototype.m=function(c){if(c.ports&&c.ports.length&&c.ports[0]){var d=c.ports[0],e=c.data.command;switch(e){case "get_client_id":d.postMessage(c.source&&c.source.id||"null");break;case "get_offline_lock":Jf(new Hf,c);break;case "get_trace_sections":c=this.h.g;this.h.g=[];d.postMessage(c);break;case "get_network_record":c=Bf(this.l,c.data.params.requestUrl);d.postMessage(c);break;case "get_compression_info":var f=c.data.params.url;(c=(this.g.performance&&this.g.performance.getEntries?this.g.performance.getEntries():
[]).find(function(k){return k.name==f}))&&d.postMessage({encodedBodySize:c.encodedBodySize||-1,decodedBodySize:c.decodedBodySize||-1,transferSize:c.transferSize||-1});d.postMessage({});break;case "clear_resource_timing_buffer":this.g.performance&&this.g.performance.clearResourceTimings&&this.g.performance.clearResourceTimings();d.postMessage({});break;default:d.postMessage({error:"Got an unsupported command: "+e})}}};
var Fe=self,lf=new function(){this.g=(new URL(E.location.toString())).searchParams},Nf=new function(){this.g=[]},Of=new function(){this.g=new Map},mf=(new URL(Fe.registration.scope)).pathname,Pf=new function(){var c=new nf,d=new Wa,e=Nf,f=Of,k=lf,l=mf;this.g=c;this.j=d;this.l=k;this.m=l;this.i=e;this.h=f},V=new Qf;V.g.addEventListener("install",V.H.bind(V),!1);V.g.addEventListener(aa,V.D.bind(V),!1);V.g.addEventListener("fetch",V.F.bind(V),!1);V.g.addEventListener("message",V.m.bind(V),!1);

}catch(e){_DumpException(e)}
// Google Inc.
